version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS test;' > /docker-entrypoint-initdb.d/init.sql;
      /entrypoint.sh --character-set-vm=utf8mb4 --collation-vm=utf8mb4_unicode_ci
      "
